config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :test_sets
  resources :test_sets
  resources :tests
  root 'principal#index'
  get '/test_set/api/:video_url', to: 'api#find_test_set_from_video'
  get '/test_set/:test_set_id/tests', to: 'tests#show_tests_for_set'
  get '/test_set/:test_set_id/tests/new', to: 'tests#new'
  get '/test_set/:test_set_id/tests/:test_id/', to: 'tests#show'
  get '/test_set/:test_set_id/tests/:test_id/edit', to: 'tests#edit'

  get 'tests/new2/:params_test_set_id' => 'tests#new'

  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  get "/logout" => "sessions#destroy", as: :logout
  get "/login/:params" =>'sessions#index'

end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :test_set
end

app/models/test_set.rb
class TestSet < ActiveRecord::Base
  has_many :tests
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :test_sets

	def self.find_or_create_with_omniauth(auth)
	user = self.where(uid: auth[:uid], provider: auth[:provider]).first_or_create
    #user = self.find_or_create_by_provider_and_uid(auth.provider, auth.uid)
    user.assign_attributes({ name: auth.info.name, email: auth.info.email, access_token: auth.credentials.token })
    user.save!
    user
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_filter :verify_authenticity_token

  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
      headers['Access-Control-Max-Age'] = '1728000'

      render :text => '', :content_type => 'text/plain'
    end
  end

  def find_test_set_from_video
    test_set = TestSet.where(video_url: params[:video_url])
    render json: test_set.to_json(include: :tests)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
      auth = request.env["omniauth.auth"]
      @user = User.find_or_create_with_omniauth(auth)
      session[:user_id] = @user.id
      redirect_to "/login/#{@user.name}"  , :notice => "Opa! Você está online!"
    end

    def failure
    	redirect_to root_path 
 	end 

	 def destroy 
	   session[:user_id] = nil 
	   redirect_to root_path
	 end 
end

app/controllers/test_sets_controller.rb
class TestSetsController < ApplicationController
  before_action :set_test_set, only: [:new2, :show, :edit, :update, :destroy]

  # GET /test_sets
  # GET /test_sets.json
  def index
    @test_sets = TestSet.all
  end

  # GET /test_sets/1
  # GET /test_sets/1.json
  def show
  end

  # GET /test_sets/new
  def new
    @test_set = TestSet.new
  end

  # GET /test_sets/1/edit
  def edit
  end

  # POST /test_sets
  # POST /test_sets.json
  def create
    
    tam = test_set_params["video_url"].size
    params_int = test_set_params
    params_int["video_url"] = test_set_params["video_url"][32..tam]
    params_int["score"] = 0
    @test_set = TestSet.new(params_int)

    respond_to do |format|
      if @test_set.save
        format.html { redirect_to @test_set, notice: 'O Quiz foi adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @test_set }
      else
        format.html { render :new }
        format.json { render json: @test_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_sets/1
  # PATCH/PUT /test_sets/1.json
  def update

    tam = test_set_params["video_url"].size
    params_int = test_set_params
    params_int["video_url"] = test_set_params["video_url"][32..tam]
    respond_to do |format|
      if @test_set.update(params_int)
        format.html { redirect_to @test_set, notice: 'O Quiz foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @test_set }
      else
        format.html { render :edit }
        format.json { render json: @test_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_sets/1
  # DELETE /test_sets/1.json
  def destroy
    @test_set.destroy
    respond_to do |format|
      format.html { redirect_to test_sets_url, notice: 'O Quiz foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_set
      @test_set = TestSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_set_params
      params.require(:test_set).permit(:description, :video_url, :score)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]
  before_filter :find_test_set

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  def show_tests_for_set
    @tests = Test.where(test_set_id: params[:test_set_id])
    render  template: "tests/index"
  end

  # GET /tests/new
  def new
    @a = params
    @test = Test.new

    @test.test_set_id = nil || @a['params_test_set_id'] || @a['test_set_id']

  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to "/test_sets/#{@test.test_set_id}" , notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to :back, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      id = params[:id] || params[:test_id]
      @test = Test.find(id)
    end

    def find_test_set
      return unless params[:test_set_id]
      @test_set = TestSet.find(params[:test_set_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:description, :question, :alternative1, :alternative2, :alternative3, :alternative4, :answer, :time, :test_set_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_sets_helper.rb
module TestSetsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/principal/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Youtube Quiz</title>

    <!-- Bootstrap Core CSS -->
    <link href="assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="assets/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">Download</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#criar">Crie um quiz</a>
                    </li>
                                        <li>
                        <a class="page-scroll" href="/auth/facebook">Login  <%= @b %></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Youtube Quiz</h1>
                        <p class="intro-text">Um aplicativo pra revolucionar o ensino online<br>ITA Code Jam</p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Sobre Youtube Quiz</h2>
                <p>Youtube Quiz é uma extensao gratis para o chrome, ele é utilizado para mostrar testes durante um video e facilitar o aprendizado</p>
                <p>Esse aplicativo foi criado durante o ITA Code Jam da RedeAlumni</p>
                <a href="/test_sets" class="btn btn-default btn-lg">Veja Quizzes já existentes</a>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Youtube Quiz</h2>
                    <p>Voce pode fazer o download da extensão do chrome na Google Store</p>
                    <a href="https://chrome.google.com/webstore/category/extensions" class="btn btn-default btn-lg">Pagina de Download</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="criar" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Crie um quiz</h2>
                <p>Crie seu próprio Quiz para os seus videos do Youtube</p>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="/test_sets/new" class="btn btn-default btn-lg"></i> <span>Criar um quiz</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
        </div>
    </footer>

    <!-- jQuery -->
    <script src="assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="assets/jquery.easing.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="assets/grayscale.js"></script>

</body>

</html>

app/views/test_sets/_form.html.erb
<%= @test_set.description %>


<%= form_for(@test_set) do |f| %>
  <% if @test_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_set.errors.count, "error") %> prohibited this test_set from being saved:</h2>

      <ul>
      <% @test_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Descrição do seu Quiz" %><br>
    <%= f.text_area :description, size: "100x10", class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label "Link pro video do Youtube" %><br>
    <%= f.text_field :video_url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'ENVIAR', class: 'btn btn-default btn-lg'%>
  </div>
<% end %>

app/views/test_sets/edit.html.erb
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Youtube Quiz</title>

  <!-- Bootstrap Core CSS -->
  <link href="../assets/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="../assets/grayscale.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2"><body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top"



          <h1>Editando esse quiz</h1>

          <%= render 'form' %>

          <%= link_to 'Voltar', @test_set %>
        </div>
      </div>
    </div>
  </div>
</header>

        </body>

app/views/test_sets/index.html.erb
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Youtube Quizzes</title>

    <!-- Bootstrap Core CSS -->
    <link href="../assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../assets/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <header class="intro">
    <div class="intro-body">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2"><body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top"

            <p id="notice"><%= notice %></p>

            <h1>Youtube Quizzes</h1>

            <table>
              <thead>
                <tr>
                  <th><h5>Descrição</h5></th>
                  <th><h5>Youtube</h5></th>
                  <th><h5>Pontuação</h5></th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @test_sets.each do |test_set| %>
        <tr>
  <style type="text/css">
  td
  {
      padding:0 50px 0 50px;
  }
  </style>

                    <td><%= test_set.description %></td>
                    <td><%= link_to 'Link', "https://www.youtube.com/watch?v=#{test_set.video_url}" %> </td>
                    <td><%= test_set.score %></td>
                    <td><%= link_to 'Show', test_set %></td>
                    <td><%= link_to 'Edit', edit_test_set_path(test_set) %></td>
                    <td><%= link_to 'Destroy', test_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

          <%= link_to 'Adicionar novo Quiz', new_test_set_path %> | <br>
          <%= link_to 'Pagina Principal', root_path %>
          </div>
        </div>
      </div>
    </div>
  </header>

          </body>


      

app/views/test_sets/new.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Youtube Quiz</title>

    <!-- Bootstrap Core CSS -->
    <link href="../assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../assets/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                      <%= render 'form' %>
                      <%= link_to 'Voltar', "/", class: 'btn btn-default btn-lg'%>
                    </div>
                </div>
            </div>
        </div>
    </header>



</body>

app/views/test_sets/show.html.erb
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Youtube Quiz</title>

  <!-- Bootstrap Core CSS -->
  <link href="../assets/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="../assets/grayscale.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>


<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2"><body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top"

          <p id="notice"><%= notice %></p>

          <p>
            <strong>Descricao:</strong>
            <%= @test_set.description %>
          </p>

          <p>
            <strong>Id do video:</strong>
            <%= @test_set.video_url %>
          </p>

          <p>
            <strong>Score:</strong>
            <%= @test_set.score %>
          </p>

          <p>
             Numero de perguntas: <%= @test_set.test_ids.count %>
          </p>

          <p>
            <%= link_to 'Criar nova pergunta para esse quiz', "/tests/new2/#{@test_set.id}
" %> |
            <%= link_to 'Editar esse quiz', edit_test_set_path(@test_set) %> |
            <%= link_to 'Perguntas', "/test_set/#{@test_set.id}/tests" %> |
            <%= link_to 'Voltar', "/" %>
          </p>

        </div>
      </div>
    </div>
  </div>
</header>



        </body>

app/views/videos/example.html.erb
teste

<%= @a %>

<%= @video %>

app/views/welcome/index.html.erb
-- Welcome to Quizlandia! -- <br>


<iframe width="560" height="315" src="//www.youtube.com/embed/DokUjuZmpCE" frameborder="0" allowfullscreen></iframe> 



<ul>
<%= link_to 'db quiz' ,  tests_path %>
<br><br>
<%= link_to 'db video' ,  videos_path %>
</ul>

<% file = File.read('/home/thiago/quiz/app/views/welcome/p.json') %>
<% data_hash = JSON.parse(file) %>
<%= data_hash['title'] %>
<%= data_hash['url'] %>
<%= data_hash['posts']['1'] %>
<%= data_hash['posts']['2'] %>